name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug project directory structure
      run: |
        echo "Root directory contents:"
        ls -la
        echo "All subdirectories:"
        find . -type d

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install .NET dependencies
      run: |
        dotnet restore backend/PerformanceManagementApi/PerformanceManagementApi/PerformanceManagementApi.csproj

    - name: Install frontend dependencies
      run: |
        cd frontend/performance-management-client
        npm install

    - name: Run frontend unit tests (Jest)
      run: |
        cd frontend/performance-management-client
        npm test -- --watchAll=false

    - name: Install Playwright
      run: |
        cd frontend/performance-management-client
        npm install -g @playwright/test
        npx playwright install

    - name: Run Playwright E2E tests
      run: |
        cd frontend/performance-management-client
        npm run build
        npx serve -s build &  # serve React build in background
        sleep 5               # wait for server to start
        npx playwright test

    - name: Setup SonarScanner for .NET
      run: |
        dotnet tool install --global dotnet-sonarscanner
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Run SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin \
          /k:"IsharaBoo_PerformanceManagementSystem" \
          /o:"isharaboo" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="https://sonarcloud.io"

        dotnet build backend/PerformanceManagementApi/PerformanceManagementApi/PerformanceManagementApi.csproj

        dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

    - name: Run backend tests (XUnit)
      run: |
        dotnet test backend/PerformanceManagementApi/PerformanceManagementApi/PerformanceManagementApi.csproj
